version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  celery:
    image: celery
    build:
      context: .
    command: celery -A your_project worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672//
    depends_on:
      - rabbitmq

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - celery

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: documentdb
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@mysql:3306/documentdb

volumes:
  rabbitmq-data:
  mysql-data:
