services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  worker:
    build:
      context: .
    command: python download/worker/worker.py
    environment:
      - PYTHONPATH=/app
    depends_on:
      - rabbitmq
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass # root solo para admin
      MYSQL_DATABASE: documentdb # base de datos
      MYSQL_USER: myuser # usuario de la app
      MYSQL_PASSWORD: mypass # clave del usuario
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - rabbitmq
    environment:
      - DATABASE_URL=mysql+pymysql://myuser:mypass@mysql:3306/documentdb

volumes:
  rabbitmq-data:
  mysql-data:
