version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  celery:
    image: celery
    build:
      context: .
    command: celery -A your_project worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672//
    depends_on:
      - rabbitmq

  flower:
    image: mher/flower
    command: flower --broker=amqp://user:password@rabbitmq:5672//
    ports:
      - '5555:5555'
    depends_on:
      - rabbitmq
      - celery
